<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/phpmailer/phpmailer/src/Exception.php';
require 'vendor/phpmailer/phpmailer/src/PHPMailer.php';
require 'vendor/phpmailer/phpmailer/src/SMTP.php';

header('Content-Type: application/json');
$response = ['status' => 'error', 'message' => 'Unknown error'];

try {
    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        if (isset($_POST['name']) && isset($_POST['email']) && isset($_POST['message']) && isset($_POST['rating'])) {
            
            // Extract form data
            $name = $_POST['name'];
            $email = $_POST['email'];
            $message = $_POST['message'];
            $rating = $_POST['rating'];
            
            // Insert data into the reviews table
            $conn = new mysqli("localhost", "root", "", "event_store");
            
            if ($conn->connect_error) {
                throw new Exception("Connection failed: " . $conn->connect_error);
            }
            
            // Prepare SQL statement
            $sql = "INSERT INTO reviews (name, email, message, rating, status, created_at) VALUES (?, ?, ?, ?, 'Pending', NOW())";
            $stmt = $conn->prepare($sql);
            
            if ($stmt) {
                $stmt->bind_param("sssi", $name, $email, $message, $rating);
                $stmt->execute();
                
                // Close statement
                $stmt->close();
                
                // Send email using PHPMailer
                $mail = new PHPMailer(true);

                // SMTP configuration
                $mail->isSMTP();
                $mail->Host       = 'smtp.gmail.com';
                $mail->SMTPAuth   = true;
                $mail->Username   = 'boardmart020@gmail.com';
                $mail->Password   = 'wojvwvhystherxdb';
                $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                $mail->Port       = 587;

                // Sender and recipient details
                $mail->setFrom('boardmart020@gmail.com', 'Board Mart');
                $mail->addAddress('boardmart020@gmail.com', 'Recipient Name');

                // Email content
                $mail->isHTML(true);
                $mail->Subject = 'New Contact Form Submission';
                
                // Professional email message body
                $mail->Body = "
                    <p><strong>Name:</strong> $name</p>
                    <p><strong>Email:</strong> $email</p>
                    <p><strong>Message:</strong></p>
                    <p>$message</p>
                    <p><strong>Rating:</strong> $rating</p>
                    <br>
                    <p>This message is automatically generated by the contact form on your website.</p>
                ";
                
                // Alternative plain text version for email clients that do not support HTML
                $mail->AltBody = "Name: $name\nEmail: $email\nMessage:\n$message\nRating: $rating";

                // Send email
                $mail->send();
                
                // Set success response
                $response = ['status' => 'success', 'message' => 'Your message and review have been sent successfully!'];
            } else {
                throw new Exception("Failed to prepare SQL statement: " . $conn->error);
            }
            
            // Close database connection
            $conn->close();
            
        } else {
            $response['message'] = 'Please fill in all fields.';
        }
    } else {
        $response['message'] = 'Invalid request method.';
    }
} catch (Exception $e) {
    $response['message'] = "Error: " . $e->getMessage();
}

echo json_encode($response);
?>
